name: ci

on:
  pull_request:
    branches:
      - "main"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          context: docker/
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
